# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6
# image: alpine

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip mercurial wget
  - sudo apt-get install pandoc

  - python -V               # Print out python version for debugging

  # - pip install virtualenv
  # - virtualenv venv
  # - source venv/bin/activate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install packages
  - conda create -q -n autogis-environment python=3.5 sphinx==1.7.9 sphinx_rtd_theme nbsphinx IPython==6.5.0 jupyter_client ipykernel matplotlib geopandas imageio
  - source activate autogis-environment

  - hg clone https://bitbucket.org/birkenfeld/sphinx-contrib/
  - cd sphinx-contrib/googleanalytics; python setup.py install; cd ../..

test:
  script:
  - sphinx-build source build/html

pages:
  script:
  - sphinx-build source build/html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
